openapi: "3.0.2"

info:
    title: "Cities API"
    description: "My API for cities"
    version: "v1.0"

servers:
- url: http://localhost:3000
  description: "Development Server"

components:
    schemas:
        stateList:
            description: "State List"
            type: array
            items:
                $ref: "#/components/schemas/state"
        state:
            description: "States"
            type: string
            enum: [
                "MA", "RI", "NH", "ME", "VT", "CT", "NY", "NJ", 
                "PA", "DE", "DC", "MD", "VA", "WV", "NC", "SC", 
                "GA", "FL", "AL", "TN", "MS", "KY", "OH", "IN", 
                "MI", "IA", "WI", "MN", "SD", "ND", "MT", "IL", 
                "MO", "KS", "NE", "LA", "AR", "OK", "TX", "CO", 
                "WY", "ID", "UT", "AZ", "NM", "NV", "CA", "HI", 
                "OR", "WA", "AK", "SG"
            ]

paths:
    /api/state/{stateId}:
        get:
            description: "Returns a list of cities from the state"
            operationId: getCitiesByState
            parameters: 
            - name: stateId
              in: path
              required: true
              schema:
                $ref: "city-schema.json#/definitions/states"
            responses:
                206:
                    description: "Partial list of citites"
                    content:
                        "application/json":
                            schema:
                                type: array
                                items:
                                    type: string
                400:
                    description: "Error"
                    content:
                        "text/plain":
                            schema:
                                type: string
    /api/states:
        get:
            description: "Returns ID list of all States"
            operationId: getStates
            responses:
                200:
                    description: "list of all states"
                    content:
                        "application/json":
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/state"
                400:
                    description: "Error"
                    content:
                        "text/plain":
                            schema:
                                type: string